services:
  mysql:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coaching
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
  backend:
    build: ./backend
    environment:
      PORT: "8080"
      MYSQL_DSN: root:root@tcp(mysql:3306)/coaching?parseTime=true
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
