CREATE DATABASE IF NOT EXISTS coaching CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE coaching;

CREATE TABLE IF NOT EXISTS members (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  picture_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  logo_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_members (
  member_id BIGINT NOT NULL,
  team_id BIGINT NOT NULL,
  UNIQUE KEY uq_member_team(member_id, team_id)
);

CREATE TABLE IF NOT EXISTS feedbacks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  target_type VARCHAR(16) NOT NULL,
  target_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
